### ISSUE TITLE
Error serializing list of Uri

### ISSUE THREAD

**Issue by Euan-McVie** [protobuf-net/protobuf-net.Grpc#132]
@mgravell - Not sure if its the exact same issue as https://github.com/protobuf-net/protobuf-net/issues/11 or not so I opened here as I'm not sure if it is an artifact of code first rather than protobuf.
Note we are using v2.4.6 of protobuf as we have 3rd party libs that don't support v3 yet.

Thanks
Euan

```
Grpc.Core.RpcException
  HResult=0x80131500
  Message=Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. InvalidOperationException: Unable to resolve a suitable Add method for System.Collections.Generic.IList`1[[System.Uri, System.Private.Uri, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.InvalidOperationException: Unable to resolve a suitable Add method for System.Collections.Generic.IList`1[[System.Uri, System.Private.Uri, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]
   at ProtoBuf.Serializers.ListDecorator..ctor(TypeModel model, Type declaredType, Type concreteType, IProtoSerializer tail, Int32 fieldNumber, Boolean writePacked, WireType packedWireType, Boolean returnList, Boolean overwriteList, Boolean supportNull) in C:\Code\protobuf-net\src\protobuf-net\Serializers\ListDecorator.cs:line 103
   at ProtoBuf.Serializers.ListDecorator.Create(TypeModel model, Type declaredType, Type concreteType, IProtoSerializer tail, Int32 fieldNumber, Boolean writePacked, WireType packedWireType, Boolean returnList, Boolean overwriteList, Boolean supportNull) in C:\Code\protobuf-net\src\protobuf-net\Serializers\ListDecorator.cs:line 62
   at ProtoBuf.Meta.ValueMember.BuildSerializer() in C:\Code\protobuf-net\src\protobuf-net\Meta\ValueMember.cs:line 555
   at ProtoBuf.Meta.MetaType.BuildSerializer() in C:\Code\protobuf-net\src\protobuf-net\Meta\MetaType.cs:line 396
   at ProtoBuf.Meta.MetaType.get_Serializer() in C:\Code\protobuf-net\src\protobuf-net\Meta\MetaType.cs:line 372
   at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Meta\RuntimeTypeModel.cs:line 803
   at ProtoBuf.Meta.TypeModel.SerializeCore(ProtoWriter writer, Object value) in C:\Code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 198
   at ProtoBuf.Meta.TypeModel.Serialize(Stream dest, Object value, SerializationContext context) in C:\Code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 222
   at ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory.Serialize[T](T value) in /_/src/protobuf-net.Grpc/Configuration/ProtoBufMarshallerFactory.cs:line 205
   at ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory.ContextualSerialize[T](T value, SerializationContext context) in /_/src/protobuf-net.Grpc/Configuration/ProtoBufMarshallerFactory.cs:line 146
   at Grpc.Net.Client.StreamExtensions.WriteMessageAsync[TMessage](Stream stream, ILogger logger, TMessage message, Action`2 serializer, String grpcEncoding, Nullable`1 maximumMessageSize, Dictionary`2 compressionProviders, CallOptions callOptions)
   at Grpc.Net.Client.Internal.PushUnaryContent`2.WriteMessageCore(ValueTask writeMessageTask)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```
Using the model:
```cs
    [ProtoContract]
    public class RegistrationRequest
    {
        [ProtoMember(1)]
        public IList<Uri> HostUris { get; }

        [ProtoMember(2)]
        public IList<string> ServiceIds { get; }

        /// <summary>
        /// Need parameterless constructor for protobuf deserialisation
        /// </summary>
        RegistrationRequest() { }

        /// <summary>
        /// Constructs a new registration request.
        /// </summary>
        public RegistrationRequest(IList<Uri> hostUris, IList<string> serviceIds)
        {
            HostUris = hostUris;
            ServiceIds = serviceIds;
        }
    }
```
And service:
```cs
    [Service("ServiceDiscovery")]
    public interface IServiceDiscovery
    {
        ValueTask<ResultDTO<string, string>> RegisterServicesAsync(RegistrationRequest request);      
    }
```

**Comment by kwyz** [comment]
Any updates ?
