### ISSUE TITLE
Use of IGrpcService - Service is unimplemented

### ISSUE THREAD

**Issue by virzak** [protobuf-net/protobuf-net.Grpc#182]
[Source](https://github.com/virzak/grpc-dotnet/tree/IGrpcService/examples/Coder)

In an effort to get rid of the deprecated WCF assembly dependencies (System.Private.ServiceModel.dll - 1846KB) I tried to switch the coder example (simplest I could find) to IGrpcService

```diff
-    [ServiceContract]
-    public interface IGreeterService
+    public interface IGreeterService : IGrpcService
     {
-        [OperationContract]
         Task<HelloReply> SayHelloAsync(HelloRequest request, CallContext context = default);
     }
```

Link to the commit:

https://github.com/virzak/grpc-dotnet/commit/30cf49ce6a395e4507966b666f89435e9b60c125#diff-acf1770e4b474b9d6be4b76a8451a8996e2f3165a803a41c309d77a41ae3ad95

But ended up getting

```
Grpc.Core.RpcException
  HResult=0x80131500
  Message=Status(StatusCode="Unimplemented", Detail="Service is unimplemented.")
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ProtoBuf.Grpc.Internal.Reshape.<UnaryTaskAsyncImpl>d__12`2.MoveNext() in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 289
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Client.Program.<Main>d__0.MoveNext() in Q:\Code\Examples\grpc-dotnet\examples\Coder\Client\Program.cs:line 34
```

The server output is:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:5001/IGreeterService/SayHello application/grpc -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - Unimplemented service'
info: Grpc.AspNetCore.Server.Internal.ServerCallHandlerFactory[1]
      Service 'IGreeterService' is unimplemented.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - Unimplemented service'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://localhost:5001/IGreeterService/SayHello application/grpc - - 200 0 application/grpc 88.6303ms
```

The original output that was produced was:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:5001/Shared.GreeterService/SayHello application/grpc -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /Shared.GreeterService/SayHello'
info: Server.GreeterService[0]
      Sending hello to GreeterClient
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /Shared.GreeterService/SayHello'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://localhost:5001/Shared.GreeterService/SayHello application/grpc - - 200 - application/grpc 191.5487ms
```

So the difference is the endpoint `/IGreeterService/SayHello` vs `/Shared.GreeterService/SayHello`

Is there a quick fix for this?

**Comment by virzak** [comment]
Just discovered that `ProtoBuf.Grpc.Configuration.ServiceAttribute` and `ProtoBuf.Grpc.Configuration.OperationAttribute` exist so that solves my issue of WCF. 

```diff
-using System.ServiceModel;
 using System.Threading.Tasks;
 using ProtoBuf.Grpc;
+using ProtoBuf.Grpc.Configuration;

 namespace Shared
 {
-    [ServiceContract]
+    [Service]
     public interface IGreeterService
     {
-        [OperationContract]
+        [Operation]
         Task<HelloReply> SayHelloAsync(HelloRequest request, CallContext context = default);
     }
 }
```

So the `IGrpcService` issue is not critical at this point.

**Comment by codymullins** [comment]
I am getting the same issue. Kept getting the service unimplemented error for the last few hours until I got to this issue. Removed the `IGrpcService` interface and viola - all works now.
