### ISSUE TITLE
SchemaGenerator produces unexpected result when using records

### ISSUE THREAD

**Issue by erikljung** [protobuf-net/protobuf-net.Grpc#186]
Hi I've noticed some unexpected behavior of `GrpcSchemaGenerator.GetSchema` when used in conjunction with C# records.

**Empty records**
The following code won't generate any messages or methods, the expected behavior would be that the method was generated and that the messages where empty. Changing any of the records like: `SomeRequest(string Foo)` will however make this work as expected. I've verified that classes doesn't behave like this.
```
public record SomeRequest;
public record SomeResponse;

[ServiceContract]
public interface ISomeService {
  Task<SomeResponse> Get(SomeRequest request);
}
```

**Collections**
Records seems to work fine as proto contracts with the exception of collections.

```
public record SomeRequest( ICollection<string> Arr )
```
Produces the unexpected:
```
message SomeRequest {
  ICollection_String arr = 1;
}
```
Where the expected output is:
```
message SomeRequest {
   repeated string arr = 1;
}
```
In order to get the expected output, the following code is needed. Notice that `[ProtoContract]` is needed and all additional fields also needs the `[property:..]` attribute.
```
[ProtoContract]
public record SomeRequest([property: ProtoMember( 1 )] ICollection<string> Arr )
```

Not 100% related to the issue above. Another problem that emerges with the use of records is the possibility to set default values. We would like to (in some short way) express that the `Arr` always should be an empty collection, just as you could with `[ProtoAfterDeserialization]` in classes, do you have any ideas on how we can achieve that while keeping the simple composition of a record?

**Comment by erikljung** [comment]
Just found that if you decorate the record with `[ProtoContract( ImplicitFields = ImplicitFields.AllPublic )]` the collection issue is solved, so that might be a pointer if there is any attempt to fix this. That does however not seem to be a sustainable workaround since the order of the members is not stable, as pointed out in https://github.com/protobuf-net/protobuf-net.Grpc/issues/176

**Comment by mgravell** [comment]
What version of protobuf-net are you using? V3 should support simple records

**Comment by erikljung** [comment]
3.0.101 and no updates available as far as I can see. Simple records seems to work fine except the collection part.

Here is a small reproduction:
```
public class Reproduction
{
	[Fact]
	public void SchemaGenerator_produces_unexpected_collection_type()
	{
		var schema = new SchemaGenerator().GetSchema( typeof( ITest ) );
		schema.Should().Match(
			"*message Req {*ICollection_String Coll = 1;*}*" );
	}
}

[ServiceContract]
public interface ITest
{
	Task Test( Req req );
}

public record Req( ICollection<string> Coll );
```

**Comment by erikljung** [comment]
Something else I discovered is that when I use `[CompatibilityLevel( CompatibilityLevel.Level300 )]` the SchemaGenerator throws exception of mixed compatibility level, which seems a bit weird (see following repro). Removing the attributes will fix this issue, but what compatibility level will then be applied?

```
public class Reproduction
{
	[Fact]
	public void SchemaGenerator_throws_when_compat_level_is_set()
	{
		When.Executing( () =>
				new SchemaGenerator().GetSchema( typeof( ITest ) ) )
			.Should().Throw<InvalidOperationException>()
			.WithMessage(
				"The tuple-like type *Inner must use a single compatiblity level, "
				+ "but 'Level200' and 'Level300' are both observed; this usually "
				+ "means it is being used in different contexts in the same model." );
	}
}

[ServiceContract]
public interface ITest
{
	Task<CollectionResponse> TestRecordCollections( CollectionRequest request );
}

[CompatibilityLevel( CompatibilityLevel.Level300 )]
public record CollectionRequest( ICollection<Inner> Coll );

[CompatibilityLevel( CompatibilityLevel.Level300 )]
public record CollectionResponse( ICollection<Inner> Coll );

[CompatibilityLevel( CompatibilityLevel.Level300 )]
public record Inner( int Int );
```

**Comment by erikljung** [comment]
Hi again @mgravell, found another related issue to this. When using the `[ProtoContract]` attribute on a record (I've would like to set a custom name), the SchemaGenerator produces an empty message. Declaring all properties with `[property: ProtoMember( n )]` or adding `ImplicitFields.AllPublic` seems to give the expected result.

Example:

Input:
```
[ProtoContract]
public record Record1( string SomeStr );

public record Record2( string SomeStr );

[ProtoContract( ImplicitFields = ImplicitFields.AllPublic )]
public record Record3( string SomeStr );

public record Record4( [property: ProtoMember( 1 )] string SomeStr );
```

Output:
```
message Record1 {
}
message Record2 {
   string SomeStr = 1;
}
message Record3 {
   string SomeStr = 1;
}
message Record4 {
   string SomeStr = 1;
}
```

**Comment by erikljung** [comment]
Another notice is that when using the `[ProtoContract]` attribute on a record, suddenly there is a need for an empty contructor, even though nothing else have changed. I understand that this can be fixed with `SkipConstructor` but it just seems a bit inconsistent -- I guess there is some magic going on when attribute is _not_ present?

```
Mar-04 14:14:30 [ERR] Grpc.AspNetCore.Server.ServerCallHandler: Error when executing service method '"TestWithAttr"'. TraceId: 6dd94d4fe61bba7448a9f1d5830f49e1{ EventId: { Id: 6, Name: "ErrorExecutingServiceMethod" }, RequestId: "0HMFTS3D30QEQ:00000003", RequestPath: "/Domain.Grpc.Models.Test.TestService/TestWithAttr", ConnectionId: "0HMFTS3D30QEQ", SpanId: "22ce3400b34164af", ParentId: "e41bd389eb4b144d" }
ProtoBuf.ProtoException: No parameterless constructor found for Domain.Grpc.Models.Test.WithAttrRequest
   at ProtoBuf.Internal.ThrowHelper.ThrowProtoException(String message, Exception inner) in /_/src/protobuf-net.Core/Internal/ThrowHelper.cs:line 70
   at ProtoBuf.Meta.TypeModel.ThrowCannotCreateInstance(Type type, Exception inner) in /_/src/protobuf-net.Core/Meta/TypeModel.cs:line 1667
   at proto_223(State& , WithAttrRequest )
   at ProtoBuf.Internal.Serializers.SimpleCompiledSerializer`1.ProtoBuf.Serializers.ISerializer<T>.Read(State& state, T value)
   at ProtoBuf.ProtoReader.State.ReadAsRoot[T](T value, ISerializer`1 serializer)
   at ProtoBuf.ProtoReader.State.DeserializeRoot[T](T value, ISerializer`1 serializer)
   at ProtoBuf.Meta.TypeModel.Deserialize[T](ReadOnlySequence`1 source, T value, Object userState)
   at ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory.ContextualDeserialize[T](DeserializationContext context)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadSingleMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)


```
