### ISSUE TITLE
How to chain DelegatingHandler with ClientFactory

### ISSUE THREAD

**Issue by noufionline** [protobuf-net/protobuf-net.Grpc#198]
I am trying to hook a delegating handler to pass access token for every request.
```csharp
   internal class Program
    {
        static async Task Main(string[] args)
        {   
            GrpcClientFactory.AllowUnencryptedHttp2 = true;

            var services = new ServiceCollection();

            services.AddCodeFirstGrpcClient<ICustomerService>(cfg =>
            {
                cfg.Address = new Uri("http://localhost:5000");
            }).AddHttpMessageHandler<RefreshTokenHandler>();
               


            var client = services.BuildServiceProvider();


            var service = client.GetService<ICustomerService>();

            List<CustomerResult> result = await service.GetCustomersAsync();
            Console.WriteLine(result.Count);

            //using (var channel = GrpcChannel.ForAddress("http://localhost:5000"))
            //{
            //    var service = channel.CreateGrpcService<ICustomerService>();
            //    List<CustomerResult> result = await service.GetCustomersAsync();
            //    Console.WriteLine(result.Count);
            //}
        }


        public class RefreshTokenHandler : DelegatingHandler
        {
            protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                //here I will pass the access token
                return base.SendAsync(request, cancellationToken);
            }
        }
    }
```

I am getting the following error

![image](https://user-images.githubusercontent.com/13216154/135045256-c8b0e0ba-fbbc-4a0f-ab39-1bc5d4ff1d28.png)

```csharp
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__4`1.<AddHttpMessageHandler>b__4_1(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass17_0.<CreateHandlerEntry>g__Configure|0(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.LoggingHttpMessageHandlerBuilderFilter.<>c__DisplayClass2_0.<Configure>b__0(HttpMessageHandlerBuilder builder)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass14_0.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name)
   at Grpc.Net.ClientFactory.Internal.DefaultGrpcClientFactory.CreateClient[TClient](String name)
   at Microsoft.Extensions.DependencyInjection.GrpcClientServiceExtensions.<>c__DisplayClass7_0`1.<AddGrpcHttpClient>b__1(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at ConsoleApp1.Program.<Main>d__0.MoveNext() in C:\Users\Noufal\source\repos\Protobuf-net.Grpc\ConsoleApp1\Program.cs:line 35
```

**Comment by flour** [comment]
Try `AddScoped<RefreshTokenHandler>()`
