### ISSUE TITLE
protobuf-net.Grpc.Native referencing issue COM Interop

### ISSUE THREAD

**Issue by kanukam** [protobuf-net/protobuf-net.Grpc#205]
The most recent version of protobuf-net.Grpc.Native (1.0.152) is dependent on protobuf-net, Version=2.4.0.0 which causes issues when utilizing a grpc client through COM interop:

The type initializer for 'DefaultProxyCache`1' threw an exception. 
System.TypeInitializationException: The type initializer for 'DefaultProxyCache`1' threw an exception. ---> System.TypeInitializationException: The type initializer for 'ProtoBuf.Grpc.Configuration.BinderConfiguration' threw an exception. ---> System.TypeInitializationException: The type initializer for 'ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'protobuf-net, Version=2.4.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67' or one of its dependencies. The system cannot find the file specified.
   at ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory..cctor()
   --- End of inner exception stack trace ---
   at ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory.get_Default()
   at ProtoBuf.Grpc.Configuration.BinderConfiguration..cctor()
   --- End of inner exception stack trace ---
   at ProtoBuf.Grpc.Configuration.BinderConfiguration.get_Default()
   at ProtoBuf.Grpc.Configuration.ClientFactory.DefaultProxyCache`1..cctor()
   --- End of inner exception stack trace ---
   at ProtoBuf.Grpc.Configuration.ClientFactory.DefaultClientFactory.CreateClient[TService](CallInvoker channel)
   at ProtoBuf.Grpc.Client.GrpcClientFactory.CreateGrpcService[TService](CallInvoker client, ClientFactory clientFactory)
   at FakeInstrumentv2.FakeInstrumentv2COM.InitializeDriver()
System.TypeInitializationException: The type initializer for 'ProtoBuf.Grpc.Configuration.BinderConfiguration' threw an exception. ---> System.TypeInitializationException: The type initializer for 'ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'protobuf-net, Version=2.4.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67' or one of its dependencies. The system cannot find the file specified.
   at ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory..cctor()
   --- End of inner exception stack trace ---
   at ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory.get_Default()
   at ProtoBuf.Grpc.Configuration.BinderConfiguration..cctor()
   --- End of inner exception stack trace ---
   at ProtoBuf.Grpc.Configuration.BinderConfiguration.get_Default()
   at ProtoBuf.Grpc.Configuration.ClientFactory.DefaultProxyCache`1..cctor()
System.TypeInitializationException: The type initializer for 'ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'protobuf-net, Version=2.4.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67' or one of its dependencies. The system cannot find the file specified.
   at ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory..cctor()
   --- End of inner exception stack trace ---
   at ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory.get_Default()
   at ProtoBuf.Grpc.Configuration.BinderConfiguration..cctor()
System.IO.FileNotFoundException: Could not load file or assembly 'protobuf-net, Version=2.4.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67' or one of its dependencies. The system cannot find the file specified.
File name: 'protobuf-net, Version=2.4.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67'
   at ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory..cctor()

**Comment by mgravell** [comment]
What is the setup here? And what version of protobuf-net are you actually
shipping? Is this perhaps .net framework, and if so: is this just an
assembly binding redirect issue?

**Comment by kanukam** [comment]
I am utilizing protobuf-net 3.0.101 on .NET Framework 4.6.1. My assembly binding redirect used in my client project is:

```
<dependentAssembly>
		<assemblyIdentity name="protobuf-net" publicKeyToken="257b51d87d2e4d67" culture="neutral" />
		<bindingRedirect oldVersion="0.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
</dependentAssembly>
```

The call that triggers the error is CreateGrpcService: 

```
var channel = new Channel("127.0.0.1", _grpcSharedConfig.TcpPort, ChannelCredentials.Insecure);

                  _logger.Info("Creating Grpc client");

                    _client = channel.CreateGrpcService<IService>();

                    _logger.Info("Grpc client created");
```

**Comment by mgravell** [comment]
Hmmm. That looks like it should work just fine. I will try to repro.

**Comment by kanukam** [comment]
Resolved with a method similar to this:
https://shrivastavaakash.github.io/blog/binding-redirects-without-config
