### ISSUE TITLE
CreateGrpcService errors on 4.7.2

### ISSUE THREAD

**Issue by BryantL** [protobuf-net/protobuf-net.Grpc#21]
After manually adding System.ServiceModel.Primitives nuget (to try and "manually" deal with PR #17)  I get the below runtime error.  Compiling and running with PR #17 causes the error to no longer occur (I suspect because some conditional compilation around .net standard 2.0 changed).  Targetting 4.7.2 with 4.7.2 installed.

`System.TypeInitializationException: The type initializer for 'DefaultProxyCache`3' threw an exception. ---> System.NotSupportedException: The invoked member is not supported before the type is created.
   at System.Reflection.Emit.TypeBuilder.GetField(String name, BindingFlags bindingAttr)
   at ProtoBuf.Grpc.Internal.ProxyEmitter.CreateFactory[TChannel,TService](Type baseType, BinderConfiguration binderConfig) in C:\Code\protobuf-net.Grpc\src\protobuf-net.Grpc\Internal\ProxyEmitter.cs:line 253
   at ProtoBuf.Grpc.Configuration.ClientFactory.DefaultProxyCache`3..cctor() in C:\Code\protobuf-net.Grpc\src\protobuf-net.Grpc\Configuration\ClientFactory.cs:line 68
   --- End of inner exception stack trace ---
   at ProtoBuf.Grpc.Configuration.ClientFactory.DefaultClientFactory.CreateClient[TBase,TService,TChannel](TChannel channel) in C:\Code\protobuf-net.Grpc\src\protobuf-net.Grpc\Configuration\ClientFactory.cs:line 76
   at ProtoBuf.Grpc.Configuration.ClientFactory.CreateClient[TService](CallInvoker channel) in C:\Code\protobuf-net.Grpc\src\protobuf-net.Grpc\Configuration\ClientFactory.cs:line 31
   at ProtoBuf.Grpc.Client.GrpcClientFactory.CreateGrpcService[TService](ChannelBase client, ClientFactory clientFactory) in C:\Code\protobuf-net.Grpc\src\protobuf-net.Grpc\Client\GrpcClientFactory.cs:line 29`

**Comment by mgravell** [comment]
Already fixed in #20 - will do a deploy either tomorrow or Monday

**Comment by BryantL** [comment]
Great!

I'll admit I missed PR #20 between when I came across this issue a week ago and when I got around to documenting/submitting it today.

Thanks for the great work!

**Comment by mgravell** [comment]
deployed; 1.0.6
