### ISSUE TITLE
Server-side streaming. How to detect and handle disconnections?

### ISSUE THREAD

**Issue by Dunge** [protobuf-net/protobuf-net.Grpc#210]
I'm using the pattern shown in the documentation with async enumerables and a bit of code I talked about in #187 using channel to push events in the foreach loop.

### Code sample:

Contract:
``` csharp
IAsyncEnumerable<Callback> SubscribeToCallback(CallContext context = default);
```

Server:
``` csharp
public IAsyncEnumerable<Callback> SubscribeToCallback(CallContext context = default) => SubscribeToCallback(context.CancellationToken, context);

private async IAsyncEnumerable<Callback> SubscribeToCallback([EnumeratorCancellation] CancellationToken cancel, CallContext context = default)
{
	// https://github.com/protobuf-net/protobuf-net.Grpc/issues/187
	var buffer = Channel.CreateUnbounded<CallbackModel>();
	EventHandler<CallbackModel> handler = async (sender, args) =>
	{
		await buffer.Writer.WriteAsync(args);
	};

	try
	{
		_service.CallbackUpdate += handler;

		while (!cancel.IsCancellationRequested)
		{
			CallbackModel result;

			try
			{
				result = await buffer.Reader.ReadAsync(cancel);
			}
			catch (OperationCanceledException)
			{
				// Normal, client disconnected
				yield break;
			}

			yield return result.Callback;
		}
	}
	finally
	{
		_service.CallbackUpdate -= handler;
	}
}
```

Client:
``` csharp
public class Client
{
	private CancellationTokenSource _callbackCancellationToken;

	private async Task CallbackHandler(IAsyncEnumerable<Callback> callbacks)
	{
		try
		{
			await foreach (var callback in callbacks)
			{
				// Handle messages here
			}
		}
		catch (RpcException ex)
		{
			if (ex.StatusCode != StatusCode.Cancelled) // Cancelled is normal, cancellationtoken got called from client side
				_faulted.OnNext(ex);
		}
		catch (Exception ex)
		{
			_faulted.OnNext(ex);
		}
	}
			
	private async Task Subscribe()
	{
		if (_callbackCancellationToken != null)
			_callbackCancellationToken.Cancel();
		_callbackCancellationToken = new CancellationTokenSource();
		var callbackHandler = Task.Run(async () => await CallbackHandler(_client.SubscribeToCallback(new CallContext(new CallOptions(cancellationToken: _callbackCancellationToken.Token)))), _callbackCancellationToken.Token);
	}
}
```

This is a bit complex, but it seems to be the proper way of doing this and was working perfectly while doing my tests locally.

If the client shut down or cancel the cancellation token, it reach the server finally clause and stop sending events. If the server shut down, the client receive an "Unavailable" RpcException and my _faulted event get triggered, which try to reconnect until it succeed (and end up calling Subscribe()).

The client also have a timer that do some kind of "keep-alive" (sending normal RPC calls every 30sec).

### Now the problem:

Obviously I'm unable to reproduce it locally, but I get a lot of reports from customers saying that Callback events don't reach them. I suspect a network infrastructure (NAT, Firewall, Proxy) is closing the long-running TCP connection used for the "Subscribe" call. I have absolutely no trace of error in my server log file, and no exception happening on the client side.

- Any idea how I could check from the client software if the callback channel get disconnected (more than just catching exceptions)?
- Any idea how I could reproduce the error on my development machine using external tools to force close the TCP socket? I did try to use TCPView and kill the connection, the RpcException get caught instantly, so that's not it..

**Comment by mgravell** [comment]
Sigh. Gotta love TCP. There are a myriad of ways in which sockets can get
severed silently. The only way you can know that a socket is still alive
is: to use it - i.e. have some kind of heartbeat, and if you are more than
trivially overdue: treat it as broken.

**Comment by Dunge** [comment]
Thanks for the reply.

Another protection I failed to mention is that I have an interceptor that add a Deadline (of 40sec) on every normal RPC call, and if I get a DeadlineExceeded gRPC exception, I trigger my Fault event which also recall my Subscribe() method after making sure server is available.

But now I realize I said something false. I _thought_ I had a keep alive RPC call every 30sec, but after double checking my code I see that it's only true in certain situations, which might explain the discrepancy between my experience and the customers. I now made sure to always call it.

Still unable to reproduce the problem on my end, but let's hope this will be enough to fix it!

**Comment by Dunge** [comment]
I managed to see it in action. What happens is that the client receive an `RpcException StatusCode.Cancelled`. As seen above in my code, I wasn't resubscribing in this situation because i expected this to be received only when the client cancel it's own CancellationToken locally (a manual voluntary disconnection), but in this case no. The `IsCancellationRequested` property is still false, so it receive a cancellation coming from the server.

I'm a bit confused as to why to server send this cancellation, since there's absolutely no event or error getting printed in the server logs. It shouldn't decide to drop active connections like that?

**Comment by Dunge** [comment]
When it happens I have this exception:
`Status(StatusCode="Cancelled", Detail="")`

As opposed to when I cancel it myself:
`Status(StatusCode="Cancelled", Detail="Call canceled by the client.")`

And here it the callstack:
```
   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.<MoveNextCore>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at ProtoBuf.Grpc.Internal.Reshape.<ServerStreamingAsyncImpl>d__14`2.MoveNext() in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 334
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at ProtoBuf.Grpc.Internal.Reshape.<ServerStreamingAsyncImpl>d__14`2.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at gRPCClient.gRPCClient.<CallbackHandler>d__65.MoveNext() in D:\Git\Sources\MyProject\GrpcClient\gRPCClient.cs:line 133
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at gRPCClient.gRPCClient.<CallbackHandler>d__65.MoveNext() in D:\Git\Sources\MyProject\GrpcClient\gRPCClient.cs:line 133
```

gRPCClient.cs:line 133 is the "await foreach" in the client code above.

**Comment by mgravell** [comment]
well, `HttpContentClientStreamReader` is entirely outside of my control (that is the MS transport channel); if there's something better we can do in `Reshape`, however: I'm all ears. Let me turn the question around: in a perfect world, what would you want us to to differently here, if we assume that `Reshape` could observe this condition and do things?

> Nothing about the server doing it.

I expect this is the client channel *simulating* a cancellation most likely [from here](https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Net.Client/Internal/HttpContentClientStreamReader.cs#L64-L74), which would be consistent with your missing message, [because here](https://github.com/grpc/grpc-dotnet/blob/7d081d7c2682c792971d851e9e88d11a8728a2aa/src/Grpc.Net.Client/Internal/GrpcCall.cs#L251)

/cc @JamesNK on thoughts on whether ^^^ should have a meaningful message

You (@Dunge) may also want to consider whether `ThrowOperationCanceledOnCancellation` is relevant to your scenario; I've not heard of it before this, but it looks like you can get that behaviour via:

``` c#
using var channel = GrpcChannel.ForAddress(address,
    new GrpcChannelOptions { ThrowOperationCanceledOnCancellation = true });
```

But again: I'm interested in your thoughts here: if `Reshape` should be handling this scenario: let me know what you think we should do differently.

**Comment by JamesNK** [comment]
HttpContext.RequestAborted is what gets triggered when the request is canceled. It can happen for a number of reasons and there isn't a good way to figure out why the request was canceled (e.g. stream abort vs connection abort).

Kestrel logs at a debug level probably have some detail about why the request was aborted.

**Comment by Dunge** [comment]
@mgravell : Oh don't worry, I don't think there's anything wrong with Reshape, in fact I barely understand its purpose. This is not a bug report, but more of a request for help. The only reason I opened the ticket here instead of in grpc-dotnet was because I used your method of having IAsyncEnumerable server streams in my code sample, which isn't "pure" grpc-dotnet so I didn't want to mix them up. But right, the cause for the cancellation is surely coming from deeper than your library layer and with that additional information it should probably have been asked in grpc-dotnet. Thank you very much for digging and finding source where that empty cancellation exception can get triggered, I searched for it myself yesterday and couldn't find it. Unfortunately, it doesn't help me much. I also looked at `ThrowOperationCanceledOnCancellation`, and honestly I have no idea what that's supposed to be, but no I don't have it set to true currently.

@JamesNK Honored to have you participating here. So if I understand correctly, the server abort the request at the HTTP layer, and the client catch this abort signal and push a gRPC Cancelled on its own. The abort signal isn't directly related to gRPC, but could be anything causing the Kestrel server to cancel the request. Unfortunately, I don't think it's safe to enable debug level logs on my production server and letting it run for (in average) 30min before the error occurs, and then dig in that huge amount of log to find it out. But thanks for the suggestion, I'll keep that in mind if I manage to reproduce it on a less active development environment, unfortunately it only seems to occurs with a high load. Meanwhile, do you have any shot in the dark supposition of what could cause this kind of request aborted? Too many parallel requests? Thread pool saturation? Or is it just normal Internet behavior that I should catch and handle as being something standard?

**Comment by Dunge** [comment]
It was much easier to reproduce than I thought, simply having no activity on the server stream for about 2 minutes trigger this cancellation. Seems to be some kind of timeout with nothing keeping the channel alive, even when connected to localhost.

I tried to set those values on Kestrel server to prevent it:

```
  webBuilder.ConfigureKestrel(serverOptions =>
  {
      serverOptions.Limits.KeepAliveTimeout = TimeSpan.FromMinutes(30);
      serverOptions.Limits.Http2.KeepAlivePingDelay = TimeSpan.FromSeconds(30);
      serverOptions.Limits.Http2.KeepAlivePingTimeout = TimeSpan.FromSeconds(60);
  });
```

It did **not** help.

I also see that the `[EnumeratorCancellation] CancellationToken` on the server method does get its `IsCancellationRequested` to true even if the client never request it.

As far as I know, an HttpClient already have the keep-alive header set to true, so not much can be done there.

At least catching the Cancelled event prevent me to have inactive connection. Still would like to prevent it from happening.

@mgravell I can close this ticket if you wish as it is not directly related to protobuf-net.Grpc, but I'm still looking for how to prevent this cancellation from happening..

**Comment by JamesNK** [comment]
Is there a proxy between the client and server app? If there is then the proxy is probably detecting there is no traffic on the request and is closing it.

**Comment by Dunge** [comment]
@JamesNK : No, this happens when connected directly to localhost with both projects running in visual studio locally.

**Comment by Dunge** [comment]
I also tried to add this on the client side:

```
  var handler = new SocketsHttpHandler
  {
      PooledConnectionIdleTimeout = Timeout.InfiniteTimeSpan,
      KeepAlivePingDelay = TimeSpan.FromSeconds(60),
      KeepAlivePingTimeout = TimeSpan.FromSeconds(30),
      EnableMultipleHttp2Connections = true,
  };

  var channel = GrpcChannel.ForAddress(server, new GrpcChannelOptions { HttpHandler = handler, DisposeHttpClient = true });
```

Didn't help either.

**Comment by JamesNK** [comment]
Something on your machine is closing the connection. It's not the gRPC client or server.

I updated the [Counter example](https://github.com/grpc/grpc-dotnet/tree/7d081d7c2682c792971d851e9e88d11a8728a2aa/examples/Counter) to wait 3 minutes between server streaming messages and it works fine with default client and Kestrel settings:
![image](https://user-images.githubusercontent.com/303201/147022694-3f3ee635-13bf-47d9-af11-8dbef611ec6a.png)

**Comment by Dunge** [comment]
Ok, thanks again for taking the time to help. It might be something related to protobuf-net.Grpc then. 
If you could please just take a final look at this.

I realized I wasn't helping my case, so I created a minimal reproducible solution: https://github.com/Dunge/ServerStreamCancelled

Just launch both projects, and wait. At some point the stream close on both side. Happening on both my work computer and my Windows11 personal computer.

Uncomment the line sending events in gRPCService.cs, and the connection remains alive.

**Comment by JamesNK** [comment]
Try using SocketsHttpHandler instead of HttpClientHandler. HttpClientHandler has some additional timeout logic in it.

**Comment by Dunge** [comment]
Well I'll be damned. Using the default `GrpcChannelOptions` without passing a client seems to work! Using a `SocketsHttpHandler` too, not sure why it didn't before in my real project, but here in the reproducible solution it doesn't disconnect anymore!

I was using a custom `HttpClient` for two reason: 1. To allow unsigned certificate in debug mode (not really important) and 2. To allow for GrpcWeb using this config:

```
  if (compatibilityMode)
  {
      grpcWebHandler = new GrpcWebHandler(GrpcWebMode.GrpcWebText, httpClientHandler);
      grpcWebHandler.HttpVersion = new Version(1, 1);
      httpClient = new HttpClient(grpcWebHandler);
  }
```

But i guess I can pass the grpcWebHandler directly as a HttpHandler.

Thank you so much!

I guess this should be added as a warning somewhere, maybe in the `HttpClient` field description to `GrpcChannelOptions` that passing a default one comes with different timeout logic than not passing any.

**Comment by JamesNK** [comment]
Great. I'm surprised this previous code didn't work: https://github.com/protobuf-net/protobuf-net.Grpc/issues/210#issuecomment-999210185

**Comment by mgravell** [comment]
Thanks for the input here @JamesNK - I learned some things
