### ISSUE TITLE
Protobuf-net.Grpc is trying to load protobuf-net version 2.4.0.0 in .NET framework?

### ISSUE THREAD

**Issue by NanWang33** [protobuf-net/protobuf-net.Grpc#231]
Hi,

I'm trying to use code first grpc on .net framework 4.7.1, and I have protobuf-net.3.0.73 dll in my build path. Yet, somehow protobuf-net.Grpc keep trying to load protobuf-net of version 2.4.0.0. 

There's no such issue when I testing things out in .net core platform. 
protobuf-net.Grpc require at least verion 2.4.6 of protobuf-net, so I don't understand why it is trying to load 2.4.0.0 here...

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'DefaultProxyCache`1' threw an exception.
  Source=protobuf-net.Grpc
  StackTrace:
   at ProtoBuf.Grpc.Configuration.ClientFactory.DefaultClientFactory.CreateClient[TService](CallInvoker channel) in /_/src/protobuf-net.Grpc/Configuration/ClientFactory.cs:line 91
   at ProtoBuf.Grpc.Client.GrpcClientFactory.CreateGrpcService[TService](CallInvoker client, ClientFactory clientFactory) in /_/src/protobuf-net.Grpc/Client/GrpcClientFactory.cs:line 37
   at ProtoBuf.Grpc.Client.GrpcClientFactory.CreateGrpcService[TService](ChannelBase client, ClientFactory clientFactory) in /_/src/protobuf-net.Grpc/Client/GrpcClientFactory.cs:line 29
   at Microsoft.Office.Substrate.CentralAdmin.GrpcService.Client.ActivityHostClient..ctor(String address) in
 ...

Inner Exception 1:
TypeInitializationException: The type initializer for 'ProtoBuf.Grpc.Configuration.BinderConfiguration' threw an exception.

Inner Exception 2:
TypeInitializationException: The type initializer for 'ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory' threw an exception.

Inner Exception 3:
**FileLoadException: Could not load file or assembly 'protobuf-net, Version=2.4.0.0, Culture=neutral,** PublicKeyToken=257b51d87d2e4d67' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by mgravell** [comment]
this is just an [assembly binding redirect problem](https://nickcraver.com/blog/2020/02/11/binding-redirects/); NuGet version 2.4.6 (and all Nuget 2.4.blah versions) are *assembly* version 2.4.0.0; to minimize disruption, I usually only change *assembly* version at majors, now. 

I didn't want protobuf-net.Grpc to force people to update protobuf-net version, so protobuf-net.Grpc only *demands* v 2.4.6 (or above); but it can use *features* from v3 when it discovers them (there are interfaces we added to v2.4.6 that aren't implemented, which are implemented in v3, if that makes sense).

This means that the package is - in terms of assembly binding - asking for 2.4.0,0, and is discovering 3.0.0.0 - and .NET Framework isn't happy about that (.NET Core doesn't care). So: you just need an assembly binding redirect from:

protobuf-net
Version=2.4.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67
to 3.0.0.0

This *should* be just:

``` xml
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="protobuf-net" publicKeyToken="257b51d87d2e4d67" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-3.0.0.0" newVersion="3.0.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by NanWang33** [comment]
Thanks so much for the fast reply!

**Comment by CD1010** [comment]
Hi, i still get this issue.  My client is running the latest version 3.1.17  I tried modifying the binding redirect   for newversion = 3.1.17 and i still get the error.  Difference is i have to use .net 4.8

I also tried rolling back protobuf-net to version 3.0.0 and no luck either

here is the error
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'DefaultProxyCache`1' threw an exception.
  Source=protobuf-net.Grpc
  StackTrace:
   at ProtoBuf.Grpc.Configuration.ClientFactory.DefaultClientFactory.CreateClient[TService](CallInvoker channel)
   at ProtoBuf.Grpc.Client.GrpcClientFactory.CreateGrpcService[TService](CallInvoker client, ClientFactory clientFactory)
   at ProtoBuf.Grpc.Client.GrpcClientFactory.CreateGrpcService[TService](ChannelBase client, ClientFactory clientFactory)
   at DotNetClient.Program.<Main>d__1.MoveNext() in C:\Source\Genesys\ProtoTypes\GRPCServer\DotNetClient\Program.cs:line 33

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
