### ISSUE TITLE
Q: Bi-directional streaming

### ISSUE THREAD

**Issue by ScottKane** [protobuf-net/protobuf-net.Grpc#234]
The only examples of this I can seem to find are using Grpc.Core giving you IAsyncStreamReader/Writer. Sorry if I'm missing something obvious here, but what is the intended way for this to work with protobuf-net? Both client/server sides of a request if possible where I have access to both the request and response streams.

**Comment by mgravell** [comment]
https://protobuf-net.github.io/protobuf-net.Grpc/gettingstarted discusses this; search for "duplex"

tl;dr: "use `IAsyncEnumerable<T>` as either the return type or the parameter type"

**Comment by ScottKane** [comment]
Ok thanks, do you support passing IObservable<T> instead? If not, is this something that could be considered?

**Comment by ScottKane** [comment]
Am I missing something with:

Client:
```c#
var requests = Observable
    .Interval(TimeSpan.FromSeconds(1))
    .Select(_ => DateTime.UtcNow.ToString(CultureInfo.InvariantCulture));

requests.Subscribe(request => Debug.Log($"[Client]: {request}"));

service.Subscribe(requests.ToAsyncEnumerable())
    .ToObservable()
    .Subscribe(response => Debug.Log($"[Server]: {response}"));
```

Server:
```c#
public IAsyncEnumerable<string> Subscribe(IAsyncEnumerable<string> requests)
{
    requests.ToObservable().Subscribe(request => Console.WriteLine($"[Client]: {request}"));

    var responses = Observable
        .Interval(TimeSpan.FromSeconds(1))
        .Select(_ => DateTime.UtcNow.ToString(CultureInfo.InvariantCulture));

    responses.Subscribe(response => Console.WriteLine($"[Server]: {response}"));
    
    return responses.ToAsyncEnumerable();
}
```

**Comment by mgravell** [comment]
Well, what happens? I'm not psychic, but using "string" won't usually work
well unless you've manually registered a marshaller for that (using UTF8,
presumably)

**Comment by ScottKane** [comment]
No I think this should have just worked as I have a simple Echo working with a string (and I also tested the stream with a contracted type), I think I have discovered the problem, I'm working in Unity which doesn't support HTTP2, so I've had to use Grpc.Web to even get things talking which I don't think supports bidi/duplex streaming but I could be wrong. I tried forcing my server to run over Http1 in the hopes of avoiding having to use Web on the client but I couldn't get it to work, it seemed to still try to force Http2, maybe there's some kestrel options for this I can dig into as an alternative.

**Comment by ScottKane** [comment]
I initially though maybe the observer or subscriber was blocking but I seem to be able to call Echo just fine either side so it's just that the server isn't getting the message at all. I would have thought I would get some form of unsupported exception if I can't use duplex in Grpc.Web but apparently not.

**Comment by ScottKane** [comment]
That said, if Grpc.Web does support duplex streaming I'm at a loss as to why the server is getting nothing here.

**Comment by mgravell** [comment]
Random question: does unity support raw TCP?  Socket and/or NetworkStream? If it does, I may have something...

**Comment by ScottKane** [comment]
They do as far as I'm aware, the Http2 problem is because they have an older version of HttpClient in their version of the BCL which causes the problem. All socket based approaches should work as normal as far as I'm aware (I've had a websocket TCP and UDP connection running in the past)

**Comment by ScottKane** [comment]
They are in the process of getting the runtime migrated to CoreCLR instead of the ancient fork of Mono they currently have which will mitigate all this in the future but we're probably a fair way off that happening. In newer versions they have at least moved to netstandard2.1 support which does help a lot for now.

**Comment by mgravell** [comment]
if it is of interest, I have an experimental gRPC client and server implementation that doesn't use HTTP at all; it uses the exact same API, so existing code should "just work"; tested locally against TCP with/without TLS/client-certs and named pipes, but it is transport agnostic. Let me know if that's something you'd be interested in exploring.

**Comment by ScottKane** [comment]
Absolutely interested, if I can't use http2 there's no real reason I need to be tied in. I'm more interested in having a strongly typed client

**Comment by mgravell** [comment]
The client code doesn't change whatsoever. Regardless of whether you're using contract-first generated client/server, or code-first (both of which could be labelled "strongly typed"): they work exactly the same. For the client, the only thing that changes is the channel creation code; if you want to give this a whirl, emphasizing that *this is experimental*: see https://github.com/protobuf-net/protobuf-net.Grpc/tree/grpclite/src/protobuf-net.GrpcLite - noting that a build of it is on NuGet

**Comment by ScottKane** [comment]
Ok awesome, I will have a play around. So by not deeply integrated with kestrel you mean I have to set up a LiteServer on top of kestrel?

**Comment by mgravell** [comment]
sorry; the package is hidden so you won't have known to update; short answer: protobuf-net.Grpc v1.0.167

`<PackageReference Include="protobuf-net.Grpc" Version="1.0.167" />`

**Comment by mgravell** [comment]
re "on top of kestrel" - yes; currently it doesn't hook into Kestrel, although I *have* written an `IDuplexPipe` hook, it we want to attach the server to Kestrel's inbuilt TCP support; short version: I couldn't figure out the code to get Kestrel to host *both* a regular gRPC server/web-site *and* a raw TCP server. If you can find that magic juice, let me know! There is an example Kestrel server here: https://github.com/protobuf-net/protobuf-net.Grpc/tree/grpclite/tests/protobuf-net.GrpcLite.Server - it isn't "pretty", because it does a lot more than you usually would in any sane process - it can run in either netfx (as a console) or .net 6 (via Kestrel), and spins up a ton of endpoints.

**Comment by mgravell** [comment]
(there's also a `ConnectionHandler` at the bottom of that file, re the `IDuplexPipe` mode, direct in Kestrel; I just didn't get around to getting that to play nicely yet)

**Comment by ScottKane** [comment]
I think if I can get it up and running there will definitely be a use for optional gRPC over TCP, for me it would definitely be nice to get things playing nice with kestrel. Where does `IDuplexPipe.AsFrames()` come from?

**Comment by ScottKane** [comment]
This is what I'm going with for now (I'm assuming as I only want to listen through kestrel this would be correct):

```c#
public static class Program
{
    public static async Task Main() =>
        await WebHost.CreateDefaultBuilder()
            .ConfigureServices(services =>
            {      
                services.AddSingleton<IRemotePlayerService, PlayerService>();

                services.AddCodeFirstGrpc();
                services.AddSingleton(s =>
                {
                    var server = new LiteServer();
                    server.ServiceBinder.AddCodeFirst(s.GetRequiredService<IRemotePlayerService>());
                    // Is there a version of this extension that automatically discovers the services?
                    // Maybe allow passing an IServiceCollection that it can resolve from
                    
                    return server;
                });
            })
            .UseKestrel(options =>
            {
                options.Listen(new IPEndPoint(IPAddress.Loopback, 5000), o => o.UseConnectionHandler<GrpcTcpHandler>());
            })
            .Configure((_, app) =>
            {
                app.UseRouting();
                app.UseEndpoints(endpoints =>
                {
                    endpoints.MapGrpcService<PlayerService>();
                });
            })
            .Build()
            .RunAsync();
}

public sealed class GrpcTcpHandler : ConnectionHandler
{
    private readonly LiteServer _server;
    public GrpcTcpHandler(LiteServer server) => _server = server;

    public override Task OnConnectedAsync(ConnectionContext connection) => _server.ListenAsync(connection.Transport.AsFrames());
}
```

**Comment by mgravell** [comment]
Nice. I wasn't far off - must have been missing a using directive for some helper extension methods. I'll see about updating some nuggets tomorrow. But: assuming you built locally: did anything work?

**Comment by ScottKane** [comment]
Rather than building the full source to get `IDuplexPipe.AsFrames()` I just decided to test with `server.ListenAsync(ConnectionFactory.ListenSocket(new IPEndPoint(IPAddress.Loopback, 5000)).AsStream().AsFrames())` for now. Simple console client is working but there is some awkwardness with async code in constructors in Unity (my client was creating the channel in constructor) that just freezes up the editor on start so I haven't been able to properly test inside Unity as of yet. A job for tomorrow I think, I will let you know how it goes.

I just took a look at https://github.com/davidfowl/MultiProtocolAspNetCore for reference and hoped it was right.

**Comment by ScottKane** [comment]
Would also be interesting to know if you could have this over UDP using `IMultiplexedConnectionBuilder`. From a game POV, allowing gRPC over both would be insanely powerful.

**Comment by mgravell** [comment]
Well, if we go to UDP, we ultimately end up either accepting a bunch of limitations, or having to implement a bunch of what TCP provides; in particular packet loss, packet size limits, and ordering. If we want those capabilities, it would be better to just use TCP rather than ... re-implement TCP over UDP, so we can assume that we're happy to lose some features. OK, so let's roll with that; thoughts:

- in normal scenarios, we'd be restricted by packet size; what the maximum **safe** packet size actually is is ... complex, but depending on how you math, could be 508, although in reality higher is generally fine
- I think we should assume that a unary request/response would want to be single-packet, so that would also need to cover headers/trailers
- for streaming request/response, we would presumably want to say separate messages can (and usually will) be in separate packets - which is fine, but then we need to accept that streaming data may be incomplete and/or out-of-order
- we'd also need to consider missing header/trailer data in streams, so we'd need to think about how termination happens in that scenario - out-of-band ping?

I guess my unstated question here is: are those limits acceptable as a consumer?

**Comment by ScottKane** [comment]
To be honest I would say that those considerations would be a fair compromise for using gRPC, like you say, streaming unordered packets is difficult to begin with but I would say it definitely adds value. For example in a game when the server receives a movement request you want the most up to date information where you are less concerned with the order. Most games have to manually set up TCP and UDP socket connections and flick between them for different requests.

These tradeoffs excluding streaming would be made regardless of using gRPC for a UDP socket so I definitely think this would be worth some investigation.

In my client I am currently creating a connection, grabbing the proxy services and registering them in DI, having the ability to just create 2 channels (one TCP and one UDP) and then simply decide the protocol by which channel I get the service from would be amazing.

**Comment by ScottKane** [comment]
I would also like to throw it out there that I think there is for sure a need for this socket based approach for gRPC. The biggest use case I can think is allowing duplex streaming from Blazor apps (where this isn't currently possible). Which would be incredible as a lot of front end frameworks use reactive/observable design which pairs so nicely with streams.

**Comment by mgravell** [comment]
Random question: is Blazor (in particular the client-side WASM variant you
cite) something you're experienced in? My weakness here is that I'm deeply
a library geek, and setting up the kind of client-side code to prove that
it works (and works well) isn't something I'm hugely familiar with. By
which I mean: I have basically zero experience in client-side Blazor, and
don't know which APIs would work well to demonstrate this. Can we just use
NetworkStream, for example?

It would also probably be a good thing to finish up the client-side proxy
generation ("generators") code, so the client doesn't need to run
reflection. Very doable.

**Comment by ScottKane** [comment]
I have been working with Blazor commercially since it launched (server first but switched to wasm as soon as it went into preview). Typically in most Blazor apps you just work with a HttpClient and call your server endpoints (normally restful). I see no reason why you couldn't use NetworkStream. The only limitation I have found in Blazor is the lack of http2 (because of browser limitations). Any socket based approach over TCP should work fine.

Getting up and running with a Blazor client is extremely simple these days, the wasm template gives a simple "FetchData" page which demonstrates calling a HttpClient injected from DI (in the template it just serves a json file located in the client itself) but the same principle applies to calling a rest server.

It basically ends up with a load of pages/components each with a load of HttpClient calls (or via an abstracted service doing the calls) that look something like this: `await Http.GetFromJsonAsync<WeatherForecast[]>("api/weather");`. As you can probably tell, there is nothing here that guarantees that the endpoint you call actually returns a `WeatherForecast[]`, or that it even exists.

Having gRPC provide a client wouldn't change to much in how you call the server (you still inject and call some service), but the guarantees you have about what is being returned without having an OpenAPI spec involved would be a night and day difference.

**Comment by ScottKane** [comment]
As for streaming specifically, I really haven't seen any streaming done between a Blazor client and a server. This is likely more a product of the technology being fairly new coupled with most of the documentation using HttpClient in examples. In future apps I would probably just use gRPC by default (the only reason I didn't previously is because while architecting my last major project, grpc-web wasn't available).

I think a lot of people are also concerned with losing the whole OpenAPI/Swagger flow as it's their only way to communicate an API's design effectively to consumers (even though with gRPC you can just give them a client which is 100000x better anyways)

**Comment by ScottKane** [comment]
https://github.com/AdrienTorris/awesome-blazor is a great place to learn about Blazor and find sample projects etc

**Comment by ScottKane** [comment]
Once there is a build of the .Pipelines package on nuget I will throw together a sample chat app or something demonstrating duplex from Blazor (assuming there's no unforeseen gotchas)

**Comment by mgravell** [comment]
https://www.nuget.org/packages/protobuf-net.GrpcLite.Pipelines/
https://www.nuget.org/packages/protobuf-net.GrpcLite/

**Comment by menaheme** [comment]
Hi,
Grpc pipelines gives me a 404

**Comment by menaheme** [comment]
Probably a nuget.org issue, works now

**Comment by ScottKane** [comment]
Yeah probably a good shout, I'm just testing in Unity now but the client connection code hangs. Am I correct in thinking with the server implementation I posted earlier that this should work? `ConnectionFactory.ConnectSocket(new IPEndPoint(IPAddress.Loopback, 5000)).AsFrames().CreateChannelAsync()`

**Comment by ScottKane** [comment]
Ahh never mind, was just Unity being stupid. Now I'm getting active refusal from the server so progress

**Comment by ScottKane** [comment]
Client:

```c#
var requests = Observable
    .Interval(TimeSpan.FromSeconds(1))
    .Select(_ => DateTime.UtcNow.ToString(CultureInfo.InvariantCulture));

requests.Subscribe(request => Debug.Log($"[Client]: {request}"));

service.Subscribe(requests.ToAsyncEnumerable())
    .ToObservable()
    .Subscribe(response => Debug.Log($"[Server]: {response}"));
```

Server:

```c#
public IAsyncEnumerable<string> Subscribe(IAsyncEnumerable<string> requests)
{
    requests
        .ToObservable()
        .Subscribe(request => Console.WriteLine($"[Client]: {request}"));

    var responses = Observable
        .Interval(TimeSpan.FromSeconds(1))
        .Select(_ => DateTime.UtcNow.ToString(CultureInfo.InvariantCulture));

    responses.Subscribe(response => Console.WriteLine($"[Server]: {response}"));
    
    return responses.ToAsyncEnumerable();
}
```

Server receives the first message from the client and then throws a `TimeoutException`:

```
[Client]: 04/10/2022 18:15:50
[Server]: 04/10/2022 18:15:50
Unhandled exception. System.TimeoutException: The operation has timed out.
   at ProtoBuf.Grpc.Lite.Internal.LiteStream`2.ThrowCancelled() in /_/src/protobuf-net.GrpcLite/Internal/LiteStream.cs:line 287
   at ProtoBuf.Grpc.Lite.Internal.LiteStream`2.ProtoBuf.Grpc.Lite.Internal.IStream.Cancel() in /_/src/protobuf-net.GrpcLite/Internal/LiteStream.cs:line 260
--- End of stack trace from previous location ---
   at ProtoBuf.Grpc.Lite.Internal.LiteStream`2.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token) in /_/src/protobuf-net.GrpcLite/Internal/LiteStream.cs:line 923
   at ProtoBuf.Grpc.Lite.Internal.LiteStream`2.MoveNextPayloadAsync() in /_/src/protobuf-net.GrpcLite/Internal/LiteStream.cs:line 401   at ProtoBuf.Grpc.Lite.Internal.LiteStream`2.<Grpc.Core.IAsyncStreamReader<TReceive>.MoveNext>g__Awaited|8_0(LiteStream`2 stream, ValueTask pending, CancellationTokenRegistration ctr) in /_/src/protobuf-net.GrpcLite/Internal/LiteStream.cs:line 103
   at ProtoBuf.Grpc.Internal.Reshape.AsAsyncEnumerable[T](IAsyncStreamReader`1 reader, CancellationToken cancellationToken)+MoveNext() in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 121
   at ProtoBuf.Grpc.Internal.Reshape.AsAsyncEnumerable[T](IAsyncStreamReader`1 reader, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.ToObservableObservable`1.<>c__DisplayClass2_0.<<Subscribe>g__Core|0>d.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToObservable.cs:line 50
--- End of stack trace from previous location ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
   at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
   at System.Reactive.AnonymousObserver`1.OnErrorCore(Exception error) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 73
   at System.Reactive.ObserverBase`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 59
   at System.Linq.AsyncEnumerable.ToObservableObservable`1.<>c__DisplayClass2_0.<<Subscribe>g__Core|0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Linq.AsyncEnumerable.ToObservableObservable`1.<>c__DisplayClass2_0.<<Subscribe>g__Core|0>d.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToObservable.cs:line 74
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by mgravell** [comment]
impossible to diagnose without something I can look at; the `IAsyncEnumerable<T>` aspect should be fine.

**Comment by ScottKane** [comment]
Hmm, I switched to the proper `System.Reactive` package in my Unity project and I'm still getting the error, I can only assume that this is something to do with being in full framework using `netstandard2.1` compatibility. Maybe the runtime is missing something it should have. Now that I think about it, I think some Runtime changes were made to support IAsyncEnumerable/IObservable that isn't yet available in Unity, guess I will have to wait for Unity to get to `net6.0`

**Comment by mgravell** [comment]
Well, I can't discuss nuances of RX in Unity - I lack knowledge of both. If
there's anything I can help with: let me know!

**Comment by ScottKane** [comment]
No worries, I will put together a sample to prove the TCP streaming in Blazor so people can see a decent use case

**Comment by ScottKane** [comment]
This is not as important outside of Unity, but as of right now because the IObservable cannot properly be converted to IAsyncEnumerable in the old full framework runtime, is there any way we can add the ability to pass a raw IObservable over gRPC instead of converting it to an IAsyncEnumerable? Sorry I'm a bit naive to the work entailed in doing this but would be happy to help. I think even outside of Unity, doing this would be a performance boost for people using Observables as they wouldn't constantly have to flip back and forth between the two.

**Comment by mgravell** [comment]
Ultimately, IAsyncEnumerable is "kinda sorta" core BCL (via nugets on netfx), and observable (RX): isn't. I do not currently have direct support for RX. We could probably add some if it is genuinely useful, but then I'd need to figure out some kind of mechanism to allow this to work without adding RX as a dependency of the core lib. Ultimately, most people: not using RX.

**Comment by ScottKane** [comment]
IObservable/IObserver (the base interfaces) exist in the BCL, it's included under System without needing System.Reactive (which contains concrete implementations and extensions).

**Comment by mgravell** [comment]
TIL, thanks. That: sounds usable. I'll take a look.

**Comment by ScottKane** [comment]
Awesome thanks!

**Comment by mgravell** [comment]
Well, if you get something working and are feeling generous: there's plenty
of space for some examples in the repo :)

**Comment by ScottKane** [comment]
> Well, if you get something working and are feeling generous: there's plenty of space for some examples in the repo :)

Currently what I was testing can't work inside Blazor as the browser doesn't support duplex streaming as it's limited to HTTP1. From what I can tell, Microsoft is trying to solve this with Web Transport, however I still don't think this would work from inside WASM
