### ISSUE TITLE
K6 load tests produce 'Incomplete message' Grpc.Core.RpcException during high-load of micro-services on DEV (Kubernetes Linux PODs)

### ISSUE THREAD

**Issue by janosjanka** [protobuf-net/protobuf-net.Grpc#241]
Hello Guys,

We are facing some GRPC communication issues in our DEV environment (Kubernetes Linux PODs) and maybe, you can give us some hints about where the source of this issue can be. To explain the situation quickly, we have some micro-services that communicate with each other using either HTTP REST or GRPC APIs. For example, both Angular front-end and K6 load tests typically call our ASP.NET Core REST API endpoints while our back-end APIs (micro-services) use GRPC for communication with each other, e.g.

```
                      K6 (JS) load test
                          | 
              Project API REST (GetDocuments) 
               /                           \
      Security API GRPC           Repository API GRPC
           (GetUser)                 (GetDocuments)       
```

There is no any special about it. Everything is working fine until we start to run our load tests on DEV, where we are always getting 'Incomplete message' exceptions on relative high load even if we changed/increased the limits on Kestrel (timeout, etc.), Http2 and GRPC client configs. E.g. our server-side config for Security API looks like this:

```JSON
  "Kestrel": {
    "Limits": {
      "KeepAliveTimeout": "00:03:10",
      "MaxRequestBodySize": 52428800,
      "Http2": {
        "KeepAlivePingDelay ": "00:00:30",
        "KeepAlivePingTimeout": "00:01:00",
        "MaxStreamsPerConnection": 100
      }
    }
  },
  "Grpc": {
    "EnableDetailedErrors": true,
    "MaxSendMessageSize": null,
    "MaxReceiveMessageSize": 52428800,
    "ResponseCompressionAlgorithm": "gzip",
    "ResponseCompressionLevel": "Fastest"
  },
```

The client is configured to use SocketsHttpHandler with EnableMultipleHttp2Connections:

```CSharp
new SocketsHttpHandler
{
    PooledConnectionIdleTimeout = TimeSpan.FromMinutes(2),
    KeepAlivePingDelay = TimeSpan.FromSeconds(30),
    KeepAlivePingTimeout = TimeSpan.FromSeconds(60),
    EnableMultipleHttp2Connections = true
};
```
... and with this retry policy:

```CSharp
new ServiceConfig
{
     MethodConfigs =
     {
          new MethodConfig
          {
               Names = { MethodName.Default },
               RetryPolicy = new RetryPolicy
               {
                    MaxAttempts = 5,
                    InitialBackoff = TimeSpan.FromSeconds(1),
                    MaxBackoff = TimeSpan.FromSeconds(5),
                    BackoffMultiplier = 2,
                    RetryableStatusCodes = { StatusCode.Unavailable }
               }
          }
     }
};
```

I would also like to mention is that we have unified our back-end service interfaces to be able to change the currently used client protocol specific implementation to another one without any code changes. So, it means that we do not use any library specific types, e.g. GRPC (Server)CallContext on the service interfaces themselves to get the current cancellation token, instead, our managers, similarly to AspNetCore Identity managers, use the current _Request.Aborted_ (cancellation token) through IHttpContextAccessor. I do not know it can be an issue but GRPC call context propagation also takes the token from the current http context when I checked the GIT source last time.

So, this is the exception what we get:

```CSharp
Status(StatusCode="Internal", Detail="Incomplete message.")

at Grpc.Net.Client.Internal.Retry.RetryCallBase`2.GetResponseAsync()
   at ProtoBuf.Grpc.Internal.Reshape.UnaryTaskAsyncImpl[TRequest,TResponse](AsyncUnaryCall`1 call, MetadataContext metadata, CancellationToken cancellationToken) in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 300
   at TransPerfect.ReefReview.Project.ProjectManager.GetUserWithGroupsAsync(String userName) in /source/src/Project/Core/Core/ProjectManager.cs:line 1616
   at TransPerfect.ReefReview.Project.ProjectManager.FindAllClientsAsync(ClientQueryOptions options) in /source/src/Project/Core/Core/ProjectManager.cs:line 607
   at TransPerfect.ReefReview.Project.ProjectController.FindAllClients(ClientQueryOptions options) in /source/src/Project/ProjectApi/Project/ProjectController.cs:line 386
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
```

**Framework**
SDK .NET **6.0.100**

**Package Versions**:
protobuf-net  **3.1.4**
protobuf-net.Grpc **1.0.152**
protobuf-net.Grpc.AspNetCore **1.0.152**
protobuf-net.Grpc.AspNetCore.Reflection **1.0.152**
Grpc.Net.Client **2.46.0**

I just suspect this 'Incomplete message' status comes from here:
[https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.AspNetCore.Server/Internal/PipeExtensions.cs#L249](https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.AspNetCore.Server/Internal/PipeExtensions.cs#L249)

On local, 3660 k6 load test requests have passed successfully but on Dev we are constantly getting these Incomplete Message errors for some reason.

**Comment by mgravell** [comment]
This message is outside of what protobuf-net has any part in - it *looks* like the transport itself has died. This comes, as you say, from 2 places in `PipeExtensions` (also L333). I wonder if @JamesNK has a view on this, or whether we should transfer this to grpc-dotnet

**Comment by JamesNK** [comment]
It the connection or request had been killed then you would have a different error. This appears to be the request body gracefully completing without sending the amount of data specified in the header. I think I have seen someone else mentioning this once in relation to HttpClient making an internal retry (I don't know the exact name).

It's really tough to know what is going on based on the available information. All we know is a request isn't sending the expect amount of data. Seeing .NET logs or Wireshark network logs would provide more insight.

**Comment by janosjanka** [comment]
Okay. I will try to collect some logs for you with DevOps and tester guys using Wireshark.

**Comment by fafafooey916** [comment]
@janosjanka have you figured out the issue? We're getting a similar error when trying to utilize our grpc services via F5 pointer.
Oddly, I can connect to the service (runs as a local windows service on the server, listens on specific port) when I point to "https://fullyqulaifiedservername/port#", and get back all data without issue (any of the three servers). 

The F5 url points to each of the three servers (all three are running). Another really odd behaviour: I have a blazor.wasm site where it makes grpc calls from the client app. The client app can make grpc calls pointing directly to the individual servers AND the F5 url. 

The incomplete message error occurs when pointing to the F5 grpc url, from a "server" originating grpc call, if that makes sense. The error occurs in/from blazor.server apps, mvc controllers, unit tests; we have success when making wasm/browser grpc calls.

**Comment by weili1977** [comment]
I got the same error during load testing. I was using a singleton GrpcChannel and the error disappeared after I switched to scoped, which means one GrpcChannel instance is created for each HTTP request. Although Microsoft's document says GrpcChannel is thread safe, there might be some bug in its implementation that is only revealed under high concurrency.  

Note that under the hood all GrpcChannel instances still share a single HttpClient. The cost to create and dispose the GrpcChannel shouldn't be too high.

**Comment by fafafooey916** [comment]
@weili1977 thank you for your response. While my question/issue stems from a different problem, I do have a question for you: are you utilizing a F5 pointer for your services? If so, are you using http1 or http2? 

The issue we're having reeks of F5 not configured properly for http2, I've just not had the time to confirm it. 

Thank you again.

**Comment by weili1977** [comment]
We are using NGINX with SSL termination. It is HTTP2.

**Comment by fafafooey916** [comment]
> We are using NGINX with SSL termination. It is HTTP2.

Thank you. Have a good day.

**Comment by fafafooey916** [comment]
@weili1977 another question for you: while getting this configured, were there any extra configurations needed on the service/client in order for your F5 calls to work? I'm finally able to get back into this; it seems ANY non-browser calls through the F5 are returning, "Incomplete Message" (currently using a unit test); this is with http1 only or http2 only specified on the services. (I'm manual changing the config and redeploying)

For Http1 attempts : client uses Grpc.Net.Client.Web.GrpcWebMode.GrpcWeb
For Http2 attempts : client uses basic servicecollection.AddCodeFirstGrpcClient..... and just setting the Address)

Either way; direct to server, no issues; to F5, "Incomplete Message".

Any pointers?
