### ISSUE TITLE
Is it possible to serialize cycle reference objects?

### ISSUE THREAD

**Issue by ComptonAlvaro** [protobuf-net/protobuf-net.Grpc#260]
I have this classes:

```
[DataContract]
public class ClaseTest2
{
    [DataMember(Order = 1)]
    public ClaseTest3 Clase3 {get; set; }
}


[DataContract]
public class ClaseTest3
{
    [DataMember(Order = 1)]
    public ClaseTest2 Clase2 { get; set; }
}



[DataContract]
public class ClaseTest4
{
    public ClaseTest4()
    {
        ClaseTest2 miClase2 = new ClaseTest2();
        ClaseTest3 miClase3 = new ClaseTest3();


        miClase2.Clase3 = miClase3;
        miClase3.Clase2 = miClase2;


        this.Clase2 = miClase2;    //If I comment this line, it works
    }

    [DataMember(Order = 1)]
    public ClaseTest2 Clase2;
}
```

but when I send the data to the client, I get an error:

```
info: Grpc.AspNetCore.Server.ServerCallHandler[17]
      Error sending message.
      ProtoBuf.ProtoException: Possible recursion detected (offset: 2 level(s)): GTS.Cmms.DemoGrpc.Service.Grpc.Comun.ClaseTest2
         at ProtoBuf.ProtoWriter.CheckRecursionStackAndPush(Object instance) in C:\Code\protobuf-net\src\protobuf-net\ProtoWriter.cs:line 298
         at ProtoBuf.ProtoWriter.StartSubItem(Object instance, ProtoWriter writer, Boolean allowFixed) in C:\Code\protobuf-net\src\protobuf-net\ProtoWriter.cs:line 309
         at ProtoBuf.ProtoWriter.StartSubItem(Object instance, ProtoWriter writer) in C:\Code\protobuf-net\src\protobuf-net\ProtoWriter.cs:line 280
         at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer) in C:\Code\protobuf-net\src\protobuf-net\ProtoWriter.cs:line 32
         at proto_7(Object , ProtoWriter )
         at ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Serializers\CompiledSerializer.cs:line 59
         at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Meta\RuntimeTypeModel.cs:line 803
         at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer) in C:\Code\protobuf-net\src\protobuf-net\ProtoWriter.cs:line 35
         at proto_5(Object , ProtoWriter )
         at ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Serializers\CompiledSerializer.cs:line 59
         at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Meta\RuntimeTypeModel.cs:line 803
         at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer) in C:\Code\protobuf-net\src\protobuf-net\ProtoWriter.cs:line 35
         at proto_7(Object , ProtoWriter )
         at ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Serializers\CompiledSerializer.cs:line 59
         at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Meta\RuntimeTypeModel.cs:line 803
         at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer) in C:\Code\protobuf-net\src\protobuf-net\ProtoWriter.cs:line 35
         at proto_5(Object , ProtoWriter )
         at ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Serializers\CompiledSerializer.cs:line 59
         at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Meta\RuntimeTypeModel.cs:line 803
         at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer) in C:\Code\protobuf-net\src\protobuf-net\ProtoWriter.cs:line 35
         at proto_7(Object , ProtoWriter )
         at ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Serializers\CompiledSerializer.cs:line 59
         at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Meta\RuntimeTypeModel.cs:line 803
         at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer) in C:\Code\protobuf-net\src\protobuf-net\ProtoWriter.cs:line 35
```

I guess it is because of the cycle reference between clase4 and clase3. I know many serializers doesn't support this kind of references. Is this the reason?

If this is the reason, are there plans to support it? Because if the server get the data from Entit Core, for example, that use instance for each entity, I have this kind of references, and if I want to transfer it to the client, I would have this problem. So one solution it would be to create DTOs, but it is one more step that could be affect to the performance.

Thanks.

**Comment by mgravell** [comment]
Fundamentally, protobuf is a tree (not graph) serialization format, and
protobuf itself does not support this scenario. In protobuf-net V2 we
kinda-sorta-maybe hacked something in that allowed this in some scenarios
(as an opt-in feature), but it was brittle, awkward, limited, and tricky to
support and use. We have deprecated that feature in v3. I strongly
recommend reworking your model to not have that requirement.

Alternatively, protobuf-net.Grpc is not actually strictly tied to protobuf;
it is possible to swap the marshaller layer (globally or for specific
types), if you have another serializer that will work better for your
scenario. However, note that gRPC does not negotiate formats - it is
expected that both ends of communication simply know in advance what the
data format incoming is.

**Comment by ComptonAlvaro** [comment]
Well, really I was thinking to another solution, perhaps using DTOs, beacuse perhaps in the deserialization it is not possible to ensure this was kept.

Really it is a small test project to see the posibilities, so any option for me it is acceptable.

**Comment by mgravell** [comment]
Again, the short answer is "no"; the longer answer is "no-ish". The "ish" part of that isn't something I want to advise or support going forward, so IMO focus on the short version.

**Comment by ComptonAlvaro** [comment]
if i don't misunderstand the short unswer, it is reworking my model to avoid this cirulcar references.

The problem is with a result that I get from Entity Core.

Suponse I have this two classes:

```
public Order
{
    long Id;
    
    .......

    List<Items> Items = new List<Items>();
}


public Items
{
    long Id;

    ......


    Order Order;
}
```

And I perform this query with EF:

```
_context.Orders
    .AsNotracking()
    .Include(X => x.Items)
    .FirstOrDefault(x => x.Id == 1);
```

In this case, the Order property of the items are populate too, and I get a ciruclar reference.

With EF Core, there is no way to avoid  this, because AsNoTracking() does't modified the Include() behavior, but in my model I would need this bidirectional relationsip. I need to can include the items of the order if I query the order directly. In this case is not so needed to populate the Order property, beacuse I can know from the order.

But if I query the Items directly, I would need to populate the Order property. This case would be something like this:

```
    _context.Items
    .AsNotracking()
    .Include(X => x.Order)
    .FirstOrDefault(x => x.IdOrder == 1);
```

So I don't know how could I reworking my model to avoid the circular reference.
