### ISSUE TITLE
Stream file from client to server in code first 

### ISSUE THREAD

**Issue by bballay-us** [protobuf-net/protobuf-net.Grpc#314]
Hi,

I am trying to create a file upload and I am a little bit lost tbh. I have following implementation 

```csharp
[ProtoContract]
public class FileChunkDetail
{
    [ProtoMember(1)]
    public byte[] Content { get; set; } = default!;
    
    [ProtoMember(2)]
    public bool IsLastChunk { get; set; }
}

[ServiceContract]
public interface IFileStorageService
{ 
    Task<StoreFileResponse> StoreFile(IAsyncEnumerable<FileChunkDetail> requestStream, CallContext context);

    Task<IAsyncEnumerable<FileChunkDetail>> DownloadFile(DownloadFileRequest request, CallContext context);
}
```

However the store file method gives me a 

```
System.InvalidOperationException : No marshaller available for System.Collections.Generic.IAsyncEnumerable`1[[US.StorageCore.Interface.FileStorage.FileChunkDetail, US.StorageCore.Interface, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
```

Am I doing something wrong ? 

Thanks !

**Comment by mgravell** [comment]
try:

    IAsyncEnumerable<FileChunkDetail> DownloadFile(DownloadFileRequest request, CallContext context);

i.e. no `Task` when using `IAsyncEnumerable<T>`

**Comment by bballay-us** [comment]
Thank you for the reply ! :) What about the StoreFIle method ? That's the one throwing the exception. 

```csharp
Task<StoreFileResponse> StoreFile(IAsyncEnumerable<FileChunkDetail> requestStream, CallContext context);
```

**Comment by mgravell** [comment]
are you 100% sure of that? as this matches a verified signature: https://github.com/protobuf-net/protobuf-net.Grpc/blob/557a7a19e578b5a6f576572b8775fc4f9c6ff86e/tests/protobuf-net.Grpc.Test/IAllOptions.cs#L95

I can try to look if you're sure - but without firing up any tools, that looks valid to me

**Comment by mgravell** [comment]
also: what target framework and library version is this?

**Comment by bballay-us** [comment]
I am using .net 7 and lib version :

<PackageReference Include="protobuf-net.Grpc" Version="1.1.1" />

**Comment by mgravell** [comment]
> Can the problem be that I am calling it from an integration test ?

It shouldn't matter. Very odd; that *should* "just work". I'll try to set up a repro.

**Comment by bballay-us** [comment]
I am attaching the whole stack trace: 

```
[xUnit.net 00:00:01.15]     US.StorageCore.IntegrationTests.FileStorage.FileUploadTests.StoreFile_Should_Uploaded_File [FAIL]
storage-core-tests                    |   Failed US.StorageCore.IntegrationTests.FileStorage.FileUploadTests.StoreFile_Should_Uploaded_File [1 ms]
storage-core-tests                    |   Error Message:
storage-core-tests                    |    System.TypeInitializationException : The type initializer for 'DefaultProxyCache`1' threw an exception.
storage-core-tests                    | ---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
storage-core-tests                    | -------- System.InvalidOperationException : No marshaller available for System.Collections.Generic.IAsyncEnumerable`1[[US.StorageCore.FileStorage.FileChunkDetail, US.StorageCore.Interface, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
storage-core-tests                    |   Stack Trace:
storage-core-tests                    |      at ProtoBuf.Grpc.Configuration.ClientFactory.DefaultClientFactory.CreateClient[TService](CallInvoker channel) in /_/src/protobuf-net.Grpc/Configuration/ClientFactory.cs:line 91
storage-core-tests                    |    at ProtoBuf.Grpc.ClientFactory.ServicesExtensions.<>c__6`1.<ConfigureCodeFirstGrpcClient>b__6_0(IServiceProvider services, CallInvoker callInvoker) in /_/src/protobuf-net.Grpc.ClientFactory/ServicesExtensions.cs:line 61
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.GrpcHttpClientBuilderExtensions.<>c__DisplayClass12_1.<ConfigureGrpcClientCreator>b__2(CallInvoker callInvoker)
storage-core-tests                    |    at Grpc.Net.ClientFactory.Internal.DefaultGrpcClientFactory.CreateClient[TClient](String name)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.GrpcClientServiceExtensions.<>c__DisplayClass7_0`1.<AddGrpcHttpClient>b__2(IServiceProvider s)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
storage-core-tests                    |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
storage-core-tests                    |    at US.StorageCore.IntegrationTests.FileStorage.FileUploadTests..ctor(FileStorageTestFixture testFixture) in /src/test/US.StorageCore.IntegrationTests/FileStorage/FileUploadTests.cs:line 17
storage-core-tests                    |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
storage-core-tests                    |    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
storage-core-tests                    | ----- Inner Stack Trace -----
storage-core-tests                    |    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
storage-core-tests                    |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
storage-core-tests                    |    at ProtoBuf.Grpc.Internal.ProxyEmitter.<EmitFactory>g__Marshaller|11_0[TService](Type forType, <>c__DisplayClass11_0`1&, <>c__DisplayClass11_1`1&) in /_/src/protobuf-net.Grpc/Internal/ProxyEmitter.cs:line 179
storage-core-tests                    |    at ProtoBuf.Grpc.Internal.ProxyEmitter.EmitFactory[TService](BinderConfiguration binderConfig) in /_/src/protobuf-net.Grpc/Internal/ProxyEmitter.cs:line 243
storage-core-tests                    |    at ProtoBuf.Grpc.Internal.ProxyEmitter.CreateFactory[TService](BinderConfiguration binderConfig) in /_/src/protobuf-net.Grpc/Internal/ProxyEmitter.cs:line 124
storage-core-tests                    |    at ProtoBuf.Grpc.Configuration.ClientFactory.DefaultProxyCache`1..cctor() in /_/src/protobuf-net.Grpc/Configuration/ClientFactory.cs:line 81
storage-core-tests                    | ----- Inner Stack Trace -----
storage-core-tests                    |    at ProtoBuf.Grpc.Internal.MarshallerCache.<GetMarshaller>g__Throw|5_0[T]() in /_/src/protobuf-net.Grpc/Internal/MarshallerCache.cs:line 39
storage-core-tests                    |    at ProtoBuf.Grpc.Internal.MarshallerCache.GetMarshaller[T]() in /_/src/protobuf-net.Grpc/Internal/MarshallerCache.cs:line 36
storage-core-tests                    |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
storage-core-tests                    |    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by mgravell** [comment]
Have you called `services.AddCodeFirstGrpc();` ?

**Comment by bballay-us** [comment]
On client side ?

**Comment by bballay-us** [comment]
So should I add <PackageReference Include="protobuf-net.Grpc.AspNetCore" Version="1.1.1" /> on the client as well  and call services.AddCodeFirstGrpc() ?

**Comment by mgravell** [comment]
ah, my bad - I thought (from services etc) we were talking server-side; you shouldn't need that client-side, indeed

**Comment by bballay-us** [comment]
Thanks! Somehow, the issue has miraculously resolved itself ... the other one im getting is 

```
ProtoBuf.Grpc.Internal.IncompleteSendRpcException : A message could not be sent because the server had already terminated the connection; this exception can be suppressed by specifying the IgnoreStreamTermination flag when creating the CallContext
```

Server is still working when tested by postman, only the code-first client has this issue .

**Comment by mgravell** [comment]
That usually means that the server returned a value before it had seen the
end of the sequence notification. Can I see the server read loop? Was it
enumerated to the end?

**Comment by bballay-us** [comment]
It was just a connection issue that I've resolved. Thank you man, you're an absolute legend !!
