### ISSUE TITLE
Question - Support methods with primitive parameters

### ISSUE THREAD

**Issue by duyang76** [protobuf-net/protobuf-net.Grpc#70]
Hi Marc, thanks for this great project. This is exactly what I was hoping how grpc is implemented in C#.

One question, is it possible to support methods w/ primitive parameters without defining DataContract  or ProtoContract for those parameters? For example, 

  [ServiceContract(Name = "Hyper.Calculator")]
  public interface ICalculator
  {
    double Multiply(double x, double y);
  }

**Comment by mgravell** [comment]
There's an existing issue open for it (and maybe even a complete PR). Short answer "yes", longer answer "yes, but it needs to be checked very carefully" - I need to think through the impact and design very carefully. But yes, that is the plan.

**Comment by duyang76** [comment]
Thanks Marc.

One more related question: in WCF, we use the ServiceKnownType attribute to centrally manage the types that can be de/serialized. Is it possible to support that in protobuf-net.Grpc? For example,

```
[ServiceKnownType("GetKnownTypes", typeof(MyKnownTypeHelper))]
[ServiceContract(Name = "Hyper.Calculator")]
public interface ICalculator
{
  MyDouble Multiply(MyXY xy);
}
```

The reason is that we have hundreds of machine generated classes/structs. If possible, we prefer not to change them (either manually or programmatically).

**Comment by mgravell** [comment]
My thought there is that configuring a protobuf model is a little more complex than just "these types"; do you have a more complete example that we can discuss more concretely? because: the details probably matter a lot here

**Comment by duyang76** [comment]
Here is the example.

```
  [ServiceKnownType(typeof(MyXY))]
  [ServiceContract(Name = "Hyper.Calculator")]
  public interface ICalculator
  {
    ProtoDouble Multiply(ProtoXY xy);
    ProtoDouble Multiply2(MyMsg msg);
  }

  [Serializable]
  public class MyXY
  {
    public double X;
    public double Y;
  }

  [DataContract]
  public class MyMsg
  {
    [DataMember(Order = 1)]
    public MyXY XY { get; set; }
  }
```

ProtoDouble and ProtoXY are standard DataContract classes, which work perfectly. Related to original question, I had to wrap MyXY class in MyMsg. I got the following exception when testing Multiply2:

Unhandled Exception: System.InvalidOperationException: No serializer defined for type: NetGrpc.MyXY
   at ProtoBuf.Meta.ValueMember.BuildSerializer()
   at ProtoBuf.Meta.MetaType.BuildSerializer()
   at ProtoBuf.Meta.MetaType.get_Serializer()
   at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest)
   at ProtoBuf.Meta.TypeModel.SerializeCore(ProtoWriter writer, Object value)
   at ProtoBuf.Meta.TypeModel.Serialize(Stream dest, Object value, SerializationContext context)
   at ProtoBuf.Grpc.Configuration.ProtoBufMarshallerFactory.Serialize[T](T value)
   at Grpc.Core.Marshaller`1.EmulateContextualSerializer(T message, SerializationContext context)
   at Grpc.Core.Internal.AsyncCallBase`2.UnsafeSerialize(TWrite msg, DefaultSerializationContext context)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at ProtoBuf.Grpc.Internal.Reshape.UnarySync[TRequest,TResponse](CallContext& context, CallInvoker invoker, Method`2 method, TRequest request, String host)
   at ProtoBuf.Grpc.Internal.Proxies.SimpleClientBase.ICalculator_Proxy_0.ICalculator.Multiply2(MyMsg )

Understandably the exception is thrown from the protobuf-net library, which expects the types are fully protobuf compatible. I am wondering if there is a way to make it work in protobuf-net.grpc. My guess is if we can make primitive types work, ServiceKnownType might also work?

**Comment by mgravell** [comment]
K; so, we need to separate two different things:

1. knowing that we *will want* to serialize `MyXY`
2. knowing *how* to serialize `MyXY`

The attribute solves "1", but that isn't the thing that we need to solve; we already know that because it is used *in the interface*. The problem is "2" - i.e. knowing *how* to serialize it. The issue here is one of configuration. Since protobuf does not pass names, it needs a reliable way of identifying members *as numbers*. There is no truly good way of doing that in the absence of external configuration, which is what `[ProtoMember(42)]`, or `[DataMember(Order=42)]` achieves.

There are *several* ways that we could determine to serialize `MyXY`, and the serializer tries a good number; a good number more can be configured manually at runtime if desired. I appreciate that it isn't always desirable to add attributes. As an example, the serializer would recognize it as a tuple-like type if you had:

``` c#
public class MyXY
{
    public MyXY() {} // the serializer doesn't care about this one
    public MyXY(double x, double y) { X = x; Y = y; }
    public double X;
    public double Y;
}
```

(as a side note; I believe this existing capability should work with C# 9 "records" without any changes)

Here it uses the fact that there is a constructor that looks like it has parameters that match (by name) each of the declared members. There are also other configuration schemes built in, for example "just use alphabetical, and assume this type will never change".

So: how would *you* serialize `MyXY`, and how would you anticipate the serializer knowing what you intended? I'm open to options, but it is more complex than just knowing which types.

**Comment by duyang76** [comment]
I got your point and I agree with you on the complexity.

One simple idea is to use C# binary serializer to convert MyXY to bytes. Most likely it is a bad design and I am not sure whether it is even doable. But if it is doable, it has a huge benefit: decouple the change of underlying protocol (wcf to grpc) and the change of data/service contracts.

Anyway, as I mentioned earlier, I wish grpc (in C#) was implemented in your way, then lots of these features could have been available out of the box...

**Comment by mgravell** [comment]
I cannot emphasize how strongly I would advise against **anything** involving `BinaryFormatter`. That way lies nothing but pain. However! It is entirely possible to customize the marshaller, and it would take me only moments to put together an example that does precisely that. I'll try and do that later purely as an example, but again: I advocate against it. Also worth nothing that protobuf-net has a recent and not yet documented feature of a callback API that is invoked the first time it sees a type, allowing a convenient hook to add your own serialization rules into protobuf-net where it applies.

**Comment by duyang76** [comment]
Hi Marc, thanks again for the thoughts. I agree with you on avoiding `BinaryFormatter`. I only consider it as a temporary hack during migration. Looking forward to your example and API feature.

**Comment by mgravell** [comment]
see example ^^^ - I'll consider whether I want to include this in `master` or not

**Comment by mgravell** [comment]
example merged, but in the integration tests only; I **strongly** advise reading the notes against `BinaryFormatter` that I've added here: https://github.com/protobuf-net/protobuf-net.Grpc/blob/master/tests/protobuf-net.Grpc.Test.Integration/CustomMarshaller.cs

**Comment by duyang76** [comment]
Hi Marc. Thanks for the example, especially the well-written notes. The capability to write custom marshaller is great. I will start to use it.

**Comment by duyang76** [comment]
Hi Marc, one more question: how is Exception being handled in protobuf-net.Grpc? (Should I start a new thread on this topic?)

**Comment by mgravell** [comment]
Probably best to (new issue)

**Comment by MarcDrexler** [comment]
Are primitive parameters in general the limitation here? Or **multiple** primitive parameters?

**Comment by mgravell** [comment]
Both, and they're two different issues. My request to remove the `T : class` constraint (which is unnecessary) from the underlying library hasn't been accepted yet, but may be in the future, so:

1. value-type singleton parameters need wrapping in a ref-type shell that is serializer-compatible with them being "naked"
2. multiple parameters need wrapping in a ref-type shell that essentially treats them as a tuple

IIRC there's an open PR that achieves "2", but I need to look at "1"

**Comment by lanfeust69** [comment]
Actually my PR addresses both, with structs and classes with same content being serialized the same way. What is not clear is if primitive types should be serialized directly, or wrapped into some kind of one-field message.

**Comment by mgravell** [comment]
K, I need to revisit the PR and refresh my understanding. Primitives (`int` etc, not message types) should ideally be wrapped in something akin to a single field `class Box<T> { T Value; }` if you see what I mean.

**Comment by Gambero81** [comment]
I'm looking for primitive parameters and multiple parameters on service method.

There are some news?

Thanks

**Comment by Gambero81** [comment]
Hi @mgravell primitive / multiple parameter feature is scheduled for short release date? Because, if not, i'm thinking to manage this feature with roslyn code analyzer library, generating wrapper methods with primitive / multiple params who call the protobuf-net.grpc method with single parameter.

Thanks

**Comment by wahmedswl** [comment]
[MagicOnion](https://github.com/Cysharp/MagicOnion) has support for direct RPC support with most of the primitive types without generating DataContract classes etc via MessagePack.

**Comment by BrunoJuchli** [comment]
The mentioned PR is probably https://github.com/protobuf-net/protobuf-net.Grpc/pull/48, right?

**Comment by Gambero81** [comment]
@BrunoJuchli yes, hope @mgravell can merge it asap, it's a very important feature
